### ISSUE TITLE
Reflected XSS (Tag Pencarian)

### ISSUE THREAD

**Issue by galehrizky** [itskodinger/kodinger-3#19]
Halo,

Sepertinya di route url search di parameter tag tidak ada validasi inputan karakter dari pengguna. Sehingga pengguna bisa memasukan payload XSS di parameter tag tersebut.

Screenshoot : https://assets.codelatte.net/20200302225204-kodingers.PNG

Impact paling parah dari bug ini adalah cookie stealing.

**Comment by nauvalazhar** [comment]
Halo, terima kasih sudah membuat issue. Kami sudah memperbaikinya [di sini](https://github.com/itskodinger/kodinger-3/commit/c3dcb7cbf4dd0cb913213e51041ba9498d0c97d1).
