### ISSUE TITLE
Tampil tombol delete komentar saat tidak login

### ISSUE THREAD

**Issue by arifai** [itskodinger/kodinger-3#23]
Halo,
Saya melihat tombol delete komentar saat saya tidak login, dan tombol tersebut bisa diklik. 

![Screenshot from 2020-03-05 13-30-32](https://user-images.githubusercontent.com/16235886/75954233-cc84d300-5ee5-11ea-92a5-7bf8786a0461.png)

Namun saat login tombol tersebut hilang/tidak ada. 

![Screenshot from 2020-03-05 13-27-34](https://user-images.githubusercontent.com/16235886/75954142-91829f80-5ee5-11ea-9cf5-3b6c323cd2b0.png)

Terima kasih.

**Comment by nauvalazhar** [comment]
Hai, terima kasih sudah melaporkan issue. Kami akan memperbaikinya sesegera mungkin.

**Comment by nauvalazhar** [comment]
Kami sudah memperbaikinya [di sini](https://github.com/itskodinger/kodinger-3/commit/a474037d02e1ae6dcf0fb8935e5dc30e6e428a7f). Terima kasih.
