### ISSUE TITLE
Tidak bisa ganti foto profile

### ISSUE THREAD

**Issue by RijalRifus17** [itskodinger/kodinger-3#24]

**Comment by nauvalazhar** [comment]
Apakah ada error?

**Comment by lramadhan** [comment]
Sepertinya tidak ada masalah, saya sudah coba mengganti foto profil dan berhasil.

**Comment by irrellia** [comment]
Iya ga bisa diganti, bakal muncul pesan error `The link format is invalid`.

**Comment by itskodinger** [comment]
Saya coba berhasil, ini pada saat apa keluar error seperti itu?

**Comment by RijalRifus17** [comment]
udah fix. ga tau kenapa aku coba ganti profile tetapi gk berubah, aku tengok lagi, berhasil berubah
