### ISSUE TITLE
Butuh pop-up saat share artikel

### ISSUE THREAD

**Issue by lramadhan** [itskodinger/kodinger-3#25]
Saya coba share (ke twitter) salah satu artikel yang ada, lalu diarahkan ke sosmed yang dituju (pada tab yang sama). Setelah selesai menulis caption dan membagikannya, tidak ada redirect ke halaman utama.

Saran saya tambah fitur pop-up untuk fitur share-nya, agar pengguna tetap membuka halaman kodinger.

**Comment by nauvalazhar** [comment]
Halo, terima kasih sudah membuat issue. Kami akan memperbaikinya secepat balasan gebetan!

**Comment by nauvalazhar** [comment]
Sudah kami perbaiki, brow!
