### ISSUE TITLE
Broken pop up

### ISSUE THREAD

**Issue by irrellia** [itskodinger/kodinger-3#29]
Pop up buat ngasih tau kalo kita punya artikel yg belum dipost kelihatan rusak di mobile.

Screenshot: 
![Screenshot](https://user-images.githubusercontent.com/51877647/76636406-93023680-657b-11ea-8970-472563f0d635.png)

**Comment by nauvalazhar** [comment]
Ah, aku belum cek. Thanks for reporting this issue!

**Comment by nauvalazhar** [comment]
Done!
